name: jlox
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.2 <3.0.0'

dev_dependencies:
  build_runner: any
  freezed: any
  lints: any
  test: any
dependencies:
  freezed_annotation: ^2.1.0
  tuple: any
